carproject/apps/car/urls.py
from django.urls import path, include

from .api import api_search
from .views import add_car, car_detail, entry_for_car, search, edit_car

urlpatterns = [
    path('api/search', api_search, name='api_search'),
    path('search/', search, name='search'),
    path('add/', add_car, name='add_car'),
    path('<int:car_id>/', car_detail, name='car_detail'),
    path('<int:car_id>/edit/', edit_car, name='edit_car'),
    path('<int:car_id>/entry_for_car/', entry_for_car, name='entry_for_car'),
]

carproject/carproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from apps.core.views import frontpage, signup


urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('signup/', signup, name='signup'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('login/', views.LoginView.as_view(template_name='core/login.html'), name='login'),
    path('admin/', admin.site.urls),
    path('dashboard/', include('apps.userprofile.urls')),
    path('notifications/', include('apps.notification.urls')),
    path('cars/', include('apps.car.urls')),
]

carproject/apps/car/models.py
from django.contrib.auth.models import User
from django.db import models


class Car(models.Model):
    brand = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    engine_size = models.CharField(max_length=100)
    horsepower = models.CharField(max_length=100)

    Gasoline = 'gasoline'
    Diesel = 'diesel'

    FuelType = (
        (Gasoline, 'gasoline'),
        (Diesel, 'diesel'),
    )

    fuel_type = models.CharField(default=Gasoline, choices=FuelType, max_length=20)
    is_hybrid = models.BooleanField(blank=True)

    created_by = models.ForeignKey(User, related_name='cars', on_delete=models.CASCADE)

    def __str__(self):
        return self.brand


class Dealership(models.Model):
    car = models.ForeignKey(Car, related_name='dealerships', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    created_by = models.ForeignKey(User, related_name='dealerships', on_delete=models.CASCADE)

carproject/apps/car/forms.py
from django import forms

from .models import Car, Dealership


class AddCarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['brand', 'model', 'engine_size', 'horsepower',
                  'fuel_type', 'is_hybrid']


class DealershipForm(forms.ModelForm):
    class Meta:
        model = Dealership
        fields = ['name', 'address']

carproject/apps/car/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AddCarForm, DealershipForm
from .models import Car

from apps.notification.utilities import create_notification


def search(request):
    return render(request, 'car/search.html')


def car_detail(request, car_id):
    car = Car.objects.get(pk=car_id)

    return render(request, 'car/car_detail.html', {'car': car})


@login_required
def entry_for_car(request, car_id):
    car = Car.objects.get(pk=car_id)

    if request.method == 'POST':
        form = DealershipForm(request.POST)

        if form.is_valid():
            dealership = form.save(commit=False)
            dealership.car = car
            dealership.created_by = request.user
            dealership.save()

            create_notification(request, car.created_by, 'dealership', extra_id=dealership.id)

            return redirect('dashboard')
    else:
        form = DealershipForm()

    return render(request, 'car/entry_for_car.html', {'form': form, 'car': car})


@login_required
def add_car(request):
    if request.method == 'POST':
        form = AddCarForm(request.POST)

        if form.is_valid():
            car = form.save(commit=False)
            car.created_by = request.user
            car.save()

            return redirect('dashboard')
    else:
        form = AddCarForm()

    return render(request, 'car/add_car.html', {'form': form})


@login_required
def edit_car(request, car_id):
    car = get_object_or_404(Car, pk=car_id, created_by=request.user)

    if request.method == 'POST':
        form = AddCarForm(request.POST, instance=car)

        if form.is_valid():
            car = form.save(commit=False)
            car.created_by = request.user
            car.save()

            return redirect('dashboard')
    else:
        form = AddCarForm(instance=car)

    return render(request, 'car/edit_car.html', {'form': form, 'car': car})

carproject/apps/car/templates/car/add_car.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="add-car-app">
    <h1 class="title">Add car</h1>

        <form method="post" action="." v-on:submit="validateForm">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Brand</label>

                <div class="control">
                    <input class="input" type="text" name="brand" id="id_brand" v-model="brand">
                </div>
            </div>

            <div class="field">
                <label>Model</label>

                <div class="control">
                    <input class="input" type="text" name="model" id="id_model" v-model="model">
                </div>
            </div>

            <div class="field">
                <label>Engine Size</label>

                <div class="control">
                    <input class="input" type="text" name="engine_size" id="id_engine_size" v-model="engine_size">
                </div>
            </div>

            <div class="field">
                <label>Horsepower</label>

                <div class="control">
                    <input class="input" type="text" name="horsepower" id="id_horsepower" v-model="horsepower">
                </div>
            </div>

            <div class="field">
                <label>Fuel Type</label>

                <div class="control">
                    <div class="select">
                        <select name="fuel_type" v-model="fuel_type">
                            <option value="">Choose fuel</option>
                            <option value="gasoline">Gasoline</option>
                            <option value="diesel">Diesel</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Is Hybrid</label>

                <div class="control">
                    <input type="checkbox" name="is_hybrid" id="id_is_hybrid" v-model="is_hybrid">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Submit</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const AddCarApp = {
        data() {
            return {
                brand: '',
                model: '',
                engine_size: '',
                fuel_type: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.brand === '') {
                    this.errors.push('The brand field is missing!')
                }

                if (this.model === '') {
                    this.errors.push('The model field is missing!')
                }

                if (this.engine_size === '') {
                    this.errors.push('The engine_size field is missing!')
                }

                if (this.fuel_type === '') {
                    this.errors.push('The fuel_type field is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(AddCarApp).mount('#add-car-app');
</script>
{% endblock %}

carproject/apps/car/templates/car/car_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">{{ car.brand }}</h1>

    <p class="is-size-4">{{ car.model }}</p>

    <p>{{ car.engine_size }}</p>

    <b>Dealership name: </b>
    {% for dealership in car.dealerships.all %}
        {{ dealership.name }}
    {% endfor %}<br>

    <a href="{% url 'entry_for_car' car.id %}" class="button is-success">Entry for car</a>
{% endblock %}

carproject/apps/car/templates/car/edit_car.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="edit-car-app">
    <h1 class="title">Edit car</h1>

        <form method="post" action="." v-on:submit="validateForm">
            {% csrf_token %}

            {% if form.errors %}
                {% for error in form.errors %}
                    <div class="notification is-danger">
                        {{ error }}
                    </div>
                {% endfor %}
            {% endif %}

            <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">
                    [[ error ]]
                </p>
            </div>

            <div class="field">
                <label>Brand</label>

                <div class="control">
                    <input class="input" type="text" name="brand" id="id_brand" v-model="brand">
                </div>
            </div>

            <div class="field">
                <label>Model</label>

                <div class="control">
                    <input class="input" type="text" name="model" id="id_model" v-model="model">
                </div>
            </div>

            <div class="field">
                <label>Engine Size</label>

                <div class="control">
                    <input class="input" type="text" name="engine_size" id="id_engine_size" v-model="engine_size">
                </div>
            </div>

            <div class="field">
                <label>Horsepower</label>

                <div class="control">
                    <input class="input" type="text" name="horsepower" id="id_horsepower" v-model="horsepower">
                </div>
            </div>

            <div class="field">
                <label>Fuel Type</label>

                <div class="control">
                    <div class="select">
                        <select name="fuel_type" v-model="fuel_type">
                            <option value="">Choose fuel</option>
                            <option value="gasoline">Gasoline</option>
                            <option value="diesel">Diesel</option>
                        </select>
                    </div>
                </div>
            </div>

            <div class="field">
                <label>Is Hybrid</label>

                <div class="control">
                    <input type="checkbox" name="is_hybrid" id="id_is_hybrid">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success">Save changes</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const EditCarApp = {
        data() {
            return {
                brand: '{{ car.brand }}',
                model: '{{ car.model }}',
                engine_size: '{{ car.engine_size }}',
                horsepower: '{{ car.horsepower }}',
                fuel_type: '{{ car.fuel_type }}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.brand === '') {
                    this.errors.push('The brand field is missing!')
                }

                if (this.model === '') {
                    this.errors.push('The model field is missing!')
                }

                if (this.engine_size === '') {
                    this.errors.push('The engine_size field is missing!')
                }

                if (this.fuel_type === '') {
                    this.errors.push('The fuel_type field is missing!')
                }

                if (this.errors.length) {
                    e.preventDefault()

                    return false
                } else {
                    return true
                }
            }
        }
    }

    Vue.createApp(EditCarApp).mount('#edit-car-app');
</script>
{% endblock %}

carproject/apps/car/templates/car/entry_for_car.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="title">Entry for car - {{ car.brand }}</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {% if form.errors %}
            {% for error in form.errors %}
                <div class="notification is-danger">
                    {{ error }}
                </div>
            {% endfor %}
        {% endif %}

        <div class="field">
            <label>Name</label>

            <div class="control">
                <input class="input" type="text" name="name" id="id_name">
            </div>
        </div>

        <div class="field">
            <label>Address</label>

            <div class="control">
                <input class="input" type="text" name="address" id="id_address">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-success">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

carproject/apps/car/templates/car/search.html
{% extends 'core/base.html' %}

{% block content %}
    <div id="search-app">
        <h1 class="title">Search</h1>

        <form @submit.prevent="performSearch()">
            <div class="columns">
                <div class="column is-4">
                    <div class="field">
                        <label>Query</label>

                        <div class="control">
                            <input type="text" name="query" class="input" v-model="query">
                        </div>
                    </div>

                    <div class="field">
                        <label>Fuel type</label>

                        <div class="control">
                            <div class="select">
                                <select name="fuel_type" v-model="fuel_type">
                                    <option value="" selected>Choose one</option>
                                    <option value="gasoline">Gasoline</option>
                                    <option value="diesel">Diesel</option>
                                </select>
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="control">
                            <button class="button is-success">Search</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <div v-if="cars.length">
            <hr>

            <div
                v-for="car in cars"
                :key="car.id"
                class="notification mt-2"
            >
                <h3 class="is-size-4">[[ car.brand ]]</h3>
                <p>[[ car.model ]]</p>

                <a :href="car.url">View details</a>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const SearchApp = {
        data() {
            return {
                query: '',
                fuel_type: '',
                cars: []
            }
        },
        delimeters: ['[[', ']]'],
        methods: {
            performSearch() {
                var data = {
                    'query': this.query,
                    'fuel_type': this.fuel_type
                }

                fetch('/cars/api/search/', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'dealership/json',
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    body: JSON.stringify(data)
                })
                .then((response) => {
                    return response.json()
                })
                .then((result) => {
                    console.log(result.cars)
                    this.cars = result.cars
                })
                .catch((error) => {
                    console.log('Error', error)
                })
            }
        }
    }

    Vue.createApp(SearchApp).mount('#search-app')
</script>
{% endblock %}